// ============================================================
// Shared data for the draft tracker. Every page loads this file
// so player info only lives in one place.
// ============================================================

const PLAYERS = [
  {pos:'RB',rank:1,player:'Jahmyr Gibbs',team:'DET',pts:366.9,ppg:21.6,projPts:387.5,projPpg:22.8},
  {pos:'RB',rank:2,player:'Bijan Robinson',team:'ATL',pts:370.8,ppg:21.8,projPts:391.8,projPpg:23.0},
  {pos:'WR',rank:1,player:'Ja\'Marr Chase',team:'CIN',pts:313.6,ppg:19.6,projPts:345.0,projPpg:20.3},
  {pos:'WR',rank:2,player:'Puka Nacua',team:'LAR',pts:375.0,ppg:23.4,projPts:373.6,projPpg:22.0},
  {pos:'RB',rank:3,player:'Christian McCaffrey',team:'SF',pts:416.6,ppg:24.5,projPts:318.3,projPpg:18.7},
  {pos:'WR',rank:3,player:'Amon-Ra St. Brown',team:'DET',pts:324.0,ppg:19.1,projPts:320.3,projPpg:18.8},
  {pos:'WR',rank:4,player:'Jaxon Smith-Njigba',team:'SEA',pts:359.9,ppg:21.2,projPts:341.9,projPpg:20.1},
  {pos:'RB',rank:4,player:'Jonathan Taylor',team:'IND',pts:362.3,ppg:21.3,projPts:330.4,projPpg:19.4},
  {pos:'WR',rank:5,player:'CeeDee Lamb',team:'DAL',pts:200.9,ppg:14.3,projPts:274.9,projPpg:16.2},
  {pos:'RB',rank:5,player:'Chase Brown',team:'CIN',pts:282.6,ppg:16.6,projPts:300.2,projPpg:17.7},
  {pos:'RB',rank:6,player:'James Cook III',team:'BUF',pts:302.2,ppg:17.8,projPts:262.0,projPpg:15.4},
  {pos:'RB',rank:7,player:'De\'Von Achane',team:'MIA',pts:322.8,ppg:20.2,projPts:317.6,projPpg:18.7},
  {pos:'WR',rank:6,player:'Justin Jefferson',team:'MIN',pts:201.5,ppg:11.9,projPts:261.1,projPpg:15.4},
  {pos:'RB',rank:8,player:'Kenneth Walker III',team:'KC',pts:191.9,ppg:11.3,projPts:244.3,projPpg:14.4},
  {pos:'RB',rank:9,player:'Ashton Jeanty',team:'LV',pts:245.1,ppg:14.4,projPts:286.7,projPpg:16.9},
  {pos:'RB',rank:10,player:'Omarion Hampton',team:'LAC',pts:135.7,ppg:15.1,projPts:234.3,projPpg:13.8},
  {pos:'WR',rank:7,player:'Drake London',team:'ATL',pts:201.9,ppg:16.8,projPts:321.1,projPpg:18.9},
  {pos:'RB',rank:11,player:'Saquon Barkley',team:'PHI',pts:232.3,ppg:14.5,projPts:258.6,projPpg:15.2},
  {pos:'TE',rank:1,player:'Brock Bowers',team:'LV',pts:176.2,ppg:14.7,projPts:243.9,projPpg:14.3},
  {pos:'RB',rank:12,player:'Derrick Henry',team:'BAL',pts:279.5,ppg:16.4,projPts:290.9,projPpg:17.1},
  {pos:'RB',rank:13,player:'Jeremiyah Love',team:'ARI',pts:0.0,ppg:0.0,projPts:231.3,projPpg:13.6},
  {pos:'TE',rank:2,player:'Trey McBride',team:'ARI',pts:315.9,ppg:18.6,projPts:273.4,projPpg:16.1},
  {pos:'RB',rank:14,player:'Kyren Williams',team:'LAR',pts:263.3,ppg:15.5,projPts:242.3,projPpg:14.3},
  {pos:'WR',rank:8,player:'Nico Collins',team:'HOU',pts:226.2,ppg:15.1,projPts:272.5,projPpg:16.0},
  {pos:'WR',rank:9,player:'A.J. Brown',team:'NE',pts:220.3,ppg:14.7,projPts:274.2,projPpg:16.1},
  {pos:'WR',rank:10,player:'Malik Nabers',team:'NYG',pts:57.1,ppg:14.3,projPts:249.0,projPpg:14.6},
  {pos:'WR',rank:11,player:'Rashee Rice',team:'KC',pts:150.1,ppg:18.8,projPts:304.1,projPpg:17.9},
  {pos:'WR',rank:12,player:'DeVonta Smith',team:'PHI',pts:201.8,ppg:11.9,projPts:239.9,projPpg:14.1},
  {pos:'WR',rank:13,player:'George Pickens',team:'DAL',pts:291.9,ppg:17.2,projPts:291.7,projPpg:17.2},
  {pos:'RB',rank:15,player:'Josh Jacobs',team:'GB',pts:237.1,ppg:15.8,projPts:244.5,projPpg:14.4},
  {pos:'WR',rank:14,player:'Chris Olave',team:'NO',pts:269.0,ppg:16.8,projPts:282.1,projPpg:16.6},
  {pos:'WR',rank:15,player:'Zay Flowers',team:'BAL',pts:243.3,ppg:14.3,projPts:256.9,projPpg:15.1},
  {pos:'RB',rank:16,player:'Breece Hall',team:'NYJ',pts:207.7,ppg:13.0,projPts:220.0,projPpg:12.9},
  {pos:'RB',rank:17,player:'Javonte Williams',team:'DAL',pts:242.8,ppg:15.2,projPts:213.5,projPpg:12.6},
  {pos:'WR',rank:16,player:'Garrett Wilson',team:'NYJ',pts:99.5,ppg:14.2,projPts:239.5,projPpg:14.1},
  {pos:'WR',rank:17,player:'Tetairoa McMillan',team:'CAR',pts:211.4,ppg:12.4,projPts:243.6,projPpg:14.3},
  {pos:'QB',rank:1,player:'Josh Allen',team:'BUF',pts:374.5,ppg:22.0,projPts:419.1,projPpg:24.7},
  {pos:'WR',rank:18,player:'Jaylen Waddle',team:'DEN',pts:194.1,ppg:12.1,projPts:212.9,projPpg:12.5},
  {pos:'WR',rank:19,player:'Emeka Egbuka',team:'TB',pts:195.7,ppg:11.5,projPts:235.5,projPpg:13.9},
  {pos:'RB',rank:18,player:'Bucky Irving',team:'TB',pts:138.5,ppg:13.8,projPts:237.1,projPpg:13.9},
  {pos:'WR',rank:20,player:'Tee Higgins',team:'CIN',pts:211.6,ppg:14.1,projPts:242.0,projPpg:14.2},
  {pos:'WR',rank:21,player:'Ladd McConkey',team:'LAC',pts:180.9,ppg:11.3,projPts:232.0,projPpg:13.6},
  {pos:'TE',rank:3,player:'Tyler Warren',team:'IND',pts:188.5,ppg:11.1,projPts:209.4,projPpg:12.3},
  {pos:'TE',rank:4,player:'Colston Loveland',team:'CHI',pts:165.1,ppg:10.3,projPts:235.7,projPpg:13.9},
  {pos:'WR',rank:22,player:'Luther Burden III',team:'CHI',pts:127.9,ppg:8.5,projPts:218.7,projPpg:12.9},
  {pos:'RB',rank:19,player:'Travis Etienne Jr.',team:'NO',pts:253.9,ppg:14.9,projPts:234.2,projPpg:13.8},
  {pos:'WR',rank:23,player:'Rome Odunze',team:'CHI',pts:146.1,ppg:12.2,projPts:204.4,projPpg:12.0},
  {pos:'WR',rank:24,player:'Terry McLaurin',team:'WAS',pts:114.2,ppg:11.4,projPts:220.1,projPpg:12.9},
  {pos:'WR',rank:25,player:'Carnell Tate',team:'TEN',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'QB',rank:2,player:'Lamar Jackson',team:'BAL',pts:221.8,ppg:17.1,projPts:379.5,projPpg:22.3},
  {pos:'QB',rank:3,player:'Jayden Daniels',team:'WAS',pts:117.1,ppg:16.7,projPts:367.1,projPpg:21.6},
  {pos:'RB',rank:20,player:'Cam Skattebo',team:'NYG',pts:127.7,ppg:16.0,projPts:239.1,projPpg:14.1},
  {pos:'RB',rank:21,player:'Quinshon Judkins',team:'CLE',pts:169.8,ppg:12.1,projPts:209.0,projPpg:12.3},
  {pos:'WR',rank:26,player:'DJ Moore',team:'BUF',pts:170.2,ppg:10.0,projPts:209.8,projPpg:12.3},
  {pos:'QB',rank:4,player:'Drake Maye',team:'NE',pts:359.9,ppg:21.2,projPts:362.0,projPpg:21.3},
  {pos:'QB',rank:5,player:'Jalen Hurts',team:'PHI',pts:305.0,ppg:19.1,projPts:365.6,projPpg:21.5},
  {pos:'WR',rank:27,player:'Mike Evans',team:'SF',pts:84.8,ppg:10.6,projPts:222.6,projPpg:13.1},
  {pos:'RB',rank:22,player:'TreVeyon Henderson',team:'NE',pts:206.2,ppg:12.1,projPts:186.1,projPpg:10.9},
  {pos:'WR',rank:28,player:'Davante Adams',team:'LAR',pts:222.9,ppg:15.9,projPts:214.0,projPpg:12.6},
  {pos:'RB',rank:23,player:'Bhayshul Tuten',team:'JAC',pts:88.6,ppg:5.9,projPts:194.5,projPpg:11.4},
  {pos:'RB',rank:24,player:'D\'Andre Swift',team:'CHI',pts:228.6,ppg:14.3,projPts:236.8,projPpg:13.9},
  {pos:'WR',rank:29,player:'Christian Watson',team:'GB',pts:132.4,ppg:13.2,projPts:197.8,projPpg:11.6},
  {pos:'WR',rank:30,player:'Parker Washington',team:'JAC',pts:184.7,ppg:11.5,projPts:199.1,projPpg:11.7},
  {pos:'WR',rank:31,player:'Jameson Williams',team:'DET',pts:219.9,ppg:12.9,projPts:223.5,projPpg:13.1},
  {pos:'RB',rank:25,player:'David Montgomery',team:'HOU',pts:166.9,ppg:9.8,projPts:199.4,projPpg:11.7},
  {pos:'RB',rank:26,player:'Jadarian Price',team:'SEA',pts:0.0,ppg:0.0,projPts:193.0,projPpg:11.4},
  {pos:'RB',rank:27,player:'Tony Pollard',team:'TEN',pts:185.8,ppg:10.9,projPts:183.0,projPpg:10.8},
  {pos:'TE',rank:5,player:'Kyle Pitts Sr.',team:'ATL',pts:210.8,ppg:12.4,projPts:215.8,projPpg:12.7},
  {pos:'TE',rank:6,player:'Sam LaPorta',team:'DET',pts:106.9,ppg:11.9,projPts:198.1,projPpg:11.7},
  {pos:'WR',rank:32,player:'Michael Pittman Jr.',team:'PIT',pts:202.4,ppg:11.9,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:33,player:'Marvin Harrison Jr.',team:'ARI',pts:127.8,ppg:10.7,projPts:204.5,projPpg:12.0},
  {pos:'TE',rank:7,player:'Harold Fannin Jr.',team:'CLE',pts:186.4,ppg:11.7,projPts:212.9,projPpg:12.5},
  {pos:'WR',rank:34,player:'DK Metcalf',team:'PIT',pts:187.2,ppg:12.5,projPts:194.7,projPpg:11.5},
  {pos:'QB',rank:6,player:'Joe Burrow',team:'CIN',pts:139.4,ppg:17.4,projPts:364.7,projPpg:21.5},
  {pos:'QB',rank:7,player:'Jaxson Dart',team:'NYG',pts:246.5,ppg:17.6,projPts:358.7,projPpg:21.1},
  {pos:'WR',rank:35,player:'Courtland Sutton',team:'DEN',pts:219.7,ppg:12.9,projPts:202.1,projPpg:11.9},
  {pos:'WR',rank:36,player:'Michael Wilson',team:'ARI',pts:220.6,ppg:13.0,projPts:0.0,projPpg:0.0},
  {pos:'QB',rank:8,player:'Trevor Lawrence',team:'JAC',pts:350.1,ppg:20.6,projPts:371.3,projPpg:21.8},
  {pos:'RB',rank:28,player:'Rhamondre Stevenson',team:'NE',pts:178.8,ppg:12.8,projPts:181.3,projPpg:10.7},
  {pos:'RB',rank:29,player:'Jonathon Brooks',team:'CAR',pts:0.0,ppg:0.0,projPts:173.4,projPpg:10.2},
  {pos:'QB',rank:9,player:'Caleb Williams',team:'CHI',pts:325.3,ppg:19.1,projPts:362.9,projPpg:21.3},
  {pos:'QB',rank:10,player:'Dak Prescott',team:'DAL',pts:323.8,ppg:19.0,projPts:375.2,projPpg:22.1},
  {pos:'QB',rank:11,player:'Bo Nix',team:'DEN',pts:315.8,ppg:18.6,projPts:328.0,projPpg:19.3},
  {pos:'WR',rank:37,player:'Josh Downs',team:'IND',pts:136.4,ppg:8.5,projPts:160.0,projPpg:9.4},
  {pos:'QB',rank:12,player:'Brock Purdy',team:'SF',pts:187.4,ppg:20.8,projPts:366.6,projPpg:21.6},
  {pos:'QB',rank:13,player:'Matthew Stafford',team:'LAR',pts:358.3,ppg:21.1,projPts:352.6,projPpg:20.7},
  {pos:'WR',rank:38,player:'Matthew Golden',team:'GB',pts:70.0,ppg:5.0,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:39,player:'Brian Thomas Jr.',team:'JAC',pts:138.8,ppg:9.9,projPts:200.8,projPpg:11.8},
  {pos:'QB',rank:14,player:'Justin Herbert',team:'LAC',pts:299.8,ppg:18.7,projPts:350.6,projPpg:20.6},
  {pos:'WR',rank:40,player:'Jakobi Meyers',team:'JAC',pts:175.8,ppg:11.0,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:41,player:'Wan\'Dale Robinson',team:'TEN',pts:217.9,ppg:13.6,projPts:170.0,projPpg:10.0},
  {pos:'WR',rank:42,player:'Jordan Addison',team:'MIN',pts:135.1,ppg:9.7,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:43,player:'Alec Pierce',team:'IND',pts:183.3,ppg:12.2,projPts:208.4,projPpg:12.3},
  {pos:'WR',rank:44,player:'Makai Lemon',team:'PHI',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'QB',rank:15,player:'Patrick Mahomes',team:'KC',pts:296.7,ppg:21.2,projPts:360.7,projPpg:21.2},
  {pos:'RB',rank:30,player:'Jaylen Warren',team:'PIT',pts:217.1,ppg:13.6,projPts:199.9,projPpg:11.8},
  {pos:'RB',rank:31,player:'J.K. Dobbins',team:'DEN',pts:115.9,ppg:11.6,projPts:181.1,projPpg:10.7},
  {pos:'RB',rank:32,player:'Kenny Gainwell',team:'TB',pts:221.3,ppg:13.0,projPts:189.2,projPpg:11.1},
  {pos:'RB',rank:33,player:'Rico Dowdle',team:'PIT',pts:216.3,ppg:12.7,projPts:189.1,projPpg:11.1},
  {pos:'TE',rank:8,player:'George Kittle',team:'SF',pts:161.5,ppg:14.7,projPts:197.3,projPpg:11.6},
  {pos:'RB',rank:34,player:'Chuba Hubbard',team:'CAR',pts:125.4,ppg:8.4,projPts:169.1,projPpg:9.9},
  {pos:'RB',rank:35,player:'Rachaad White',team:'WAS',pts:143.0,ppg:8.4,projPts:0.0,projPpg:0.0},
  {pos:'TE',rank:9,player:'Tucker Kraft',team:'GB',pts:117.2,ppg:14.6,projPts:199.2,projPpg:11.7},
  {pos:'TE',rank:10,player:'Dallas Goedert',team:'PHI',pts:185.1,ppg:12.3,projPts:214.7,projPpg:12.6},
  {pos:'TE',rank:11,player:'Travis Kelce',team:'KC',pts:193.2,ppg:11.4,projPts:197.2,projPpg:11.6},
  {pos:'RB',rank:36,player:'RJ Harvey',team:'DEN',pts:206.6,ppg:12.2,projPts:188.0,projPpg:11.1},
  {pos:'RB',rank:37,player:'Blake Corum',team:'LAR',pts:122.2,ppg:7.2,projPts:0.0,projPpg:0.0},
  {pos:'QB',rank:16,player:'Kyler Murray',team:'MIN',pts:80.8,ppg:16.2,projPts:329.6,projPpg:19.4},
  {pos:'WR',rank:45,player:'Jayden Reed',team:'GB',pts:48.5,ppg:6.9,projPts:0.0,projPpg:0.0},
  {pos:'TE',rank:12,player:'Dalton Kincaid',team:'BUF',pts:126.1,ppg:10.5,projPts:178.5,projPpg:10.5},
  {pos:'TE',rank:13,player:'Jake Ferguson',team:'DAL',pts:188.1,ppg:11.1,projPts:182.2,projPpg:10.7},
  {pos:'TE',rank:14,player:'Mark Andrews',team:'BAL',pts:131.0,ppg:7.7,projPts:189.2,projPpg:11.1},
  {pos:'TE',rank:15,player:'T.J. Hockenson',team:'MIN',pts:112.8,ppg:7.5,projPts:130.0,projPpg:7.6},
  {pos:'RB',rank:38,player:'Aaron Jones Sr.',team:'MIN',pts:118.7,ppg:9.9,projPts:159.5,projPpg:9.4},
  {pos:'WR',rank:46,player:'Jordyn Tyson',team:'NO',pts:0.0,ppg:0.0,projPts:40.0,projPpg:2.4},
  {pos:'WR',rank:47,player:'KC Concepcion',team:'CLE',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:39,player:'Jacory Croskey-Merritt',team:'WAS',pts:140.3,ppg:8.3,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:48,player:'Xavier Worthy',team:'KC',pts:109.9,ppg:7.9,projPts:0.0,projPpg:0.0},
  {pos:'TE',rank:16,player:'Kenyon Sadiq',team:'NYJ',pts:0.0,ppg:0.0,projPts:133.7,projPpg:7.9},
  {pos:'TE',rank:17,player:'Isaiah Likely',team:'NYG',pts:61.7,ppg:4.4,projPts:195.4,projPpg:11.5},
  {pos:'WR',rank:49,player:'Jalen Coker',team:'CAR',pts:90.4,ppg:8.2,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:50,player:'Quentin Johnston',team:'LAC',pts:171.2,ppg:12.2,projPts:191.5,projPpg:11.3},
  {pos:'WR',rank:51,player:'Romeo Doubs',team:'NE',pts:165.4,ppg:10.3,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:52,player:'Stefon Diggs',team:'WAS',pts:210.3,ppg:12.4,projPts:155.0,projPpg:9.1},
  {pos:'TE',rank:18,player:'Hunter Henry',team:'NE',pts:178.8,ppg:10.5,projPts:154.0,projPpg:9.1},
  {pos:'RB',rank:40,player:'Kyle Monangai',team:'CHI',pts:146.7,ppg:8.6,projPts:156.4,projPpg:9.2},
  {pos:'QB',rank:17,player:'Tyler Shough',team:'NO',pts:164.0,ppg:14.9,projPts:324.1,projPpg:19.1},
  {pos:'WR',rank:53,player:'Deebo Samuel Sr.',team:'SF',pts:188.2,ppg:11.8,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:41,player:'Woody Marks',team:'HOU',pts:151.1,ppg:9.4,projPts:145.0,projPpg:8.5},
  {pos:'RB',rank:42,player:'Zach Charbonnet',team:'SEA',pts:181.4,ppg:11.3,projPts:140.0,projPpg:8.2},
  {pos:'WR',rank:54,player:'Khalil Shakir',team:'BUF',pts:166.4,ppg:10.4,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:43,player:'Tank Bigsby',team:'PHI',pts:53.8,ppg:3.4,projPts:95.0,projPpg:5.6},
  {pos:'WR',rank:55,player:'Chris Godwin Jr.',team:'TB',pts:83.0,ppg:9.2,projPts:197.6,projPpg:11.6},
  {pos:'WR',rank:56,player:'Jerry Jeudy',team:'CLE',pts:120.7,ppg:7.1,projPts:0.0,projPpg:0.0},
  {pos:'QB',rank:18,player:'Jared Goff',team:'DET',pts:305.1,ppg:17.9,projPts:350.0,projPpg:20.6},
  {pos:'RB',rank:44,player:'Jordan Mason',team:'MIN',pts:128.9,ppg:8.1,projPts:150.0,projPpg:8.8},
  {pos:'QB',rank:19,player:'Daniel Jones',team:'IND',pts:234.4,ppg:18.0,projPts:338.3,projPpg:19.9},
  {pos:'WR',rank:57,player:'Rashid Shaheed',team:'SEA',pts:156.6,ppg:8.7,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:45,player:'Alvin Kamara',team:'NO',pts:100.7,ppg:9.2,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:46,player:'Chris Rodriguez Jr.',team:'JAC',pts:92.0,ppg:7.1,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:47,player:'Brian Robinson Jr.',team:'ATL',pts:62.5,ppg:3.7,projPts:0.0,projPpg:0.0},
  {pos:'QB',rank:20,player:'Baker Mayfield',team:'TB',pts:282.9,ppg:16.6,projPts:346.1,projPpg:20.4},
  {pos:'RB',rank:48,player:'Isiah Pacheco',team:'DET',pts:87.3,ppg:6.7,projPts:0.0,projPpg:0.0},
  {pos:'QB',rank:21,player:'Malik Willis',team:'MIA',pts:51.1,ppg:12.8,projPts:328.4,projPpg:19.3},
  {pos:'WR',rank:58,player:'De\'Zhaun Stribling',team:'SF',pts:0.0,ppg:0.0,projPts:60.0,projPpg:3.5},
  {pos:'WR',rank:59,player:'Jalen McMillan',team:'TB',pts:29.9,ppg:7.5,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:60,player:'Calvin Ridley',team:'TEN',pts:47.3,ppg:6.8,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:61,player:'Denzel Boston',team:'CLE',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:62,player:'Travis Hunter',team:'JAC',pts:63.8,ppg:9.1,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:63,player:'Adonai Mitchell',team:'NYJ',pts:87.9,ppg:5.5,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:64,player:'Germie Bernard',team:'PIT',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:65,player:'Jalen Nailor',team:'LV',pts:100.7,ppg:5.9,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:66,player:'Tre Tucker',team:'LV',pts:161.7,ppg:9.5,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:49,player:'Ray Davis',team:'BUF',pts:64.1,ppg:3.8,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:50,player:'Tyrone Tracy Jr.',team:'NYG',pts:160.8,ppg:10.7,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:51,player:'Mike Washington Jr.',team:'LV',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'TE',rank:19,player:'Juwan Johnson',team:'NO',pts:179.9,ppg:10.6,projPts:177.7,projPpg:10.5},
  {pos:'RB',rank:52,player:'Tyler Allgeier',team:'ARI',pts:123.0,ppg:7.2,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:53,player:'Keaton Mitchell',team:'LAC',pts:55.4,ppg:4.3,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:54,player:'Dylan Sampson',team:'CLE',pts:87.6,ppg:5.8,projPts:0.0,projPpg:0.0},
  {pos:'TE',rank:20,player:'Terrance Ferguson',team:'LAR',pts:52.1,ppg:4.0,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:67,player:'Omar Cooper Jr.',team:'NYJ',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:68,player:'Rashod Bateman',team:'BAL',pts:55.4,ppg:4.3,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:69,player:'Jauan Jennings',team:'MIN',pts:173.3,ppg:11.6,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:70,player:'Tank Dell',team:'HOU',pts:0.0,ppg:0.0,projPts:130.0,projPpg:7.6},
  {pos:'RB',rank:55,player:'Tyjae Spears',team:'TEN',pts:111.7,ppg:8.6,projPts:0.0,projPpg:0.0},
  {pos:'QB',rank:22,player:'Jordan Love',team:'GB',pts:241.3,ppg:16.1,projPts:315.5,projPpg:18.6},
  {pos:'RB',rank:56,player:'Braelon Allen',team:'NYJ',pts:15.3,ppg:3.8,projPts:0.0,projPpg:0.0},
  {pos:'K',rank:1,player:'Brandon Aubrey',team:'DAL',pts:187.6,ppg:11.0,projPts:154.0,projPpg:9.1},
  {pos:'K',rank:2,player:'Cameron Dicker',team:'LAC',pts:170.0,ppg:10.0,projPts:143.0,projPpg:8.4},
  {pos:'K',rank:3,player:'Jason Myers',team:'SEA',pts:202.0,ppg:11.9,projPts:167.0,projPpg:9.8},
  {pos:'K',rank:4,player:'Harrison Mevis',team:'LAR',pts:82.0,ppg:9.1,projPts:142.0,projPpg:8.4},
  {pos:'K',rank:5,player:'Ka\'imi Fairbairn',team:'HOU',pts:194.0,ppg:12.9,projPts:156.0,projPpg:9.2},
  {pos:'K',rank:6,player:'Eddy Pineiro',team:'SF',pts:140.0,ppg:10.0,projPts:130.0,projPpg:7.6},
  {pos:'K',rank:7,player:'Harrison Butker',team:'KC',pts:149.0,ppg:8.8,projPts:134.0,projPpg:7.9},
  {pos:'K',rank:8,player:'Cam Little',team:'JAC',pts:164.0,ppg:9.6,projPts:135.0,projPpg:7.9},
  {pos:'K',rank:9,player:'Jake Bates',team:'DET',pts:152.0,ppg:8.9,projPts:146.0,projPpg:8.6},
  {pos:'K',rank:10,player:'Tyler Loop',team:'BAL',pts:144.0,ppg:8.5,projPts:136.0,projPpg:8.0},
  {pos:'K',rank:11,player:'Cairo Santos',team:'CHI',pts:132.0,ppg:8.8,projPts:143.0,projPpg:8.4},
  {pos:'K',rank:12,player:'Will Reichard',team:'MIN',pts:159.0,ppg:9.4,projPts:141.0,projPpg:8.3},
  {pos:'RB',rank:57,player:'Jordan James',team:'SF',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'TE',rank:21,player:'Brenton Strange',team:'JAC',pts:118.0,ppg:9.8,projPts:179.9,projPpg:10.6},
  {pos:'RB',rank:58,player:'James Conner',team:'ARI',pts:33.3,ppg:8.3,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:59,player:'Justice Hill',team:'BAL',pts:65.2,ppg:6.5,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:71,player:'Zachariah Branch',team:'ATL',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'QB',rank:23,player:'Cam Ward',team:'TEN',pts:193.7,ppg:11.4,projPts:276.3,projPpg:16.3},
  {pos:'QB',rank:24,player:'C.J. Stroud',team:'HOU',pts:216.7,ppg:15.5,projPts:323.6,projPpg:19.0},
  {pos:'WR',rank:72,player:'Darnell Mooney',team:'NYG',pts:82.3,ppg:5.5,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:73,player:'Tre Harris',team:'LAC',pts:69.4,ppg:4.1,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:74,player:'Ryan Flournoy',team:'DAL',pts:114.0,ppg:7.6,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:75,player:'Antonio Williams',team:'WAS',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:76,player:'Jaylin Noel',team:'HOU',pts:68.4,ppg:4.0,projPts:0.0,projPpg:0.0},
  {pos:'TE',rank:22,player:'Pat Freiermuth',team:'PIT',pts:113.6,ppg:6.7,projPts:127.0,projPpg:7.5},
  {pos:'TE',rank:23,player:'Dalton Schultz',team:'HOU',pts:177.7,ppg:10.5,projPts:166.4,projPpg:9.8},
  {pos:'WR',rank:77,player:'Xavier Legette',team:'CAR',pts:89.3,ppg:6.0,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:78,player:'Jack Bech',team:'LV',pts:42.4,ppg:2.7,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:79,player:'Isaac TeSlaa',team:'DET',pts:75.9,ppg:4.5,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:80,player:'Chris Bell',team:'MIA',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'TE',rank:24,player:'Chig Okonkwo',team:'WAS',pts:124.0,ppg:7.3,projPts:137.2,projPpg:8.1},
  {pos:'RB',rank:60,player:'Jonah Coleman',team:'DEN',pts:0.0,ppg:0.0,projPts:60.0,projPpg:3.5},
  {pos:'RB',rank:61,player:'Kaelon Black',team:'SF',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:62,player:'Kaytron Allen',team:'WAS',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'TE',rank:25,player:'Gunnar Helm',team:'TEN',pts:91.7,ppg:5.7,projPts:99.4,projPpg:5.8},
  {pos:'RB',rank:63,player:'Kimani Vidal',team:'LAC',pts:117.9,ppg:9.1,projPts:0.0,projPpg:0.0},
  {pos:'TE',rank:26,player:'AJ Barner',team:'SEA',pts:147.3,ppg:8.7,projPts:144.2,projPpg:8.5},
  {pos:'QB',rank:25,player:'Sam Darnold',team:'SEA',pts:249.4,ppg:14.7,projPts:329.5,projPpg:19.4},
  {pos:'QB',rank:26,player:'Bryce Young',team:'CAR',pts:229.0,ppg:14.3,projPts:309.2,projPpg:18.2},
  {pos:'QB',rank:27,player:'Fernando Mendoza',team:'LV',pts:0.0,ppg:0.0,projPts:212.6,projPpg:12.5},
  {pos:'RB',rank:64,player:'Nicholas Singleton',team:'TEN',pts:0.0,ppg:0.0,projPts:55.0,projPpg:3.2},
  {pos:'RB',rank:65,player:'Demond Claiborne',team:'MIN',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:81,player:'Malik Washington',team:'MIA',pts:116.7,ppg:6.9,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:66,player:'Jaylen Wright',team:'MIA',pts:48.2,ppg:4.4,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:67,player:'Ollie Gordon II',team:'MIA',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:82,player:'Jalen Tolbert',team:'MIA',pts:46.3,ppg:3.6,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:83,player:'Cooper Kupp',team:'SEA',pts:117.3,ppg:7.3,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:84,player:'Caleb Douglas',team:'MIA',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:85,player:'Kayshon Boutte',team:'NE',pts:124.1,ppg:8.9,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:86,player:'Keenan Allen',team:'IND',pts:182.7,ppg:10.7,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:87,player:'Ja\'Kobi Lane',team:'BAL',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:88,player:'Ted Hurst',team:'TB',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:89,player:'Keon Coleman',team:'BUF',pts:102.4,ppg:7.9,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:68,player:'Adam Randall',team:'BAL',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:69,player:'Samaje Perine',team:'CIN',pts:77.9,ppg:5.2,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:70,player:'LeQuint Allen',team:'JAC',pts:24.8,ppg:1.5,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:71,player:'MarShawn Lloyd',team:'GB',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:72,player:'Jaydon Blue',team:'DAL',pts:20.4,ppg:4.1,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:73,player:'George Holani',team:'SEA',pts:20.8,ppg:2.1,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:74,player:'Ty Johnson',team:'BUF',pts:100.3,ppg:5.9,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:75,player:'Emari Demercado',team:'KC',pts:58.3,ppg:4.5,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:76,player:'Isaiah Davis',team:'NYJ',pts:71.2,ppg:4.5,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:77,player:'Emmett Johnson',team:'KC',pts:0.0,ppg:0.0,projPts:50.0,projPpg:2.9},
  {pos:'RB',rank:78,player:'Chris Brooks',team:'GB',pts:32.7,ppg:1.9,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:79,player:'Sean Tucker',team:'TB',pts:91.4,ppg:5.4,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:80,player:'DJ Giddens',team:'IND',pts:9.6,ppg:1.1,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:90,player:'Dontayvion Wicks',team:'PHI',pts:75.8,ppg:5.4,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:91,player:'Savion Williams',team:'GB',pts:25.5,ppg:2.1,projPts:0.0,projPpg:0.0},
  {pos:'K',rank:13,player:'Evan McPherson',team:'CIN',pts:136.0,ppg:8.0,projPts:134.0,projPpg:7.9},
  {pos:'K',rank:14,player:'Nick Folk',team:'ATL',pts:127.0,ppg:7.9,projPts:151.0,projPpg:8.9},
  {pos:'TE',rank:27,player:'Oronde Gadsden',team:'LAC',pts:131.4,ppg:8.8,projPts:133.0,projPpg:7.8},
  {pos:'TE',rank:28,player:'Greg Dulcich',team:'MIA',pts:62.8,ppg:6.3,projPts:144.3,projPpg:8.5},
  {pos:'TE',rank:29,player:'Cade Otton',team:'TB',pts:122.2,ppg:7.6,projPts:160.7,projPpg:9.5},
  {pos:'WR',rank:92,player:'Pat Bryant',team:'DEN',pts:74.8,ppg:5.0,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:93,player:'Tory Horton',team:'SEA',pts:65.1,ppg:8.1,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:94,player:'Elijah Sarratt',team:'BAL',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:95,player:'Dyami Brown',team:'WAS',pts:49.7,ppg:3.3,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:81,player:'Malik Davis',team:'DAL',pts:40.6,ppg:4.1,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:82,player:'Emanuel Wilson',team:'SEA',pts:94.5,ppg:5.6,projPts:0.0,projPpg:0.0},
  {pos:'QB',rank:28,player:'Geno Smith',team:'NYJ',pts:190.9,ppg:12.7,projPts:264.5,projPpg:15.6},
  {pos:'QB',rank:29,player:'Aaron Rodgers',team:'PIT',pts:234.2,ppg:14.6,projPts:244.3,projPpg:14.4},
  {pos:'QB',rank:30,player:'Jacoby Brissett',team:'ARI',pts:235.4,ppg:16.8,projPts:301.7,projPpg:17.7},
  {pos:'QB',rank:31,player:'Deshaun Watson',team:'CLE',pts:0.0,ppg:0.0,projPts:212.9,projPpg:12.5},
  {pos:'WR',rank:96,player:'Darius Slayton',team:'NYG',pts:98.8,ppg:7.1,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:97,player:'Treylon Burks',team:'WAS',pts:29.0,ppg:3.6,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:98,player:'Tyquan Thornton',team:'KC',pts:80.8,ppg:5.8,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:99,player:'Andrei Iosivas',team:'CIN',pts:89.9,ppg:5.3,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:100,player:'Jahan Dotson',team:'ATL',pts:50.2,ppg:3.0,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:83,player:'Will Shipley',team:'PHI',pts:17.5,ppg:1.2,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:84,player:'Devin Singletary',team:'NYG',pts:108.8,ppg:6.4,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:85,player:'Tyler Badie',team:'DEN',pts:35.4,ppg:2.2,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:86,player:'Tahj Brooks',team:'CIN',pts:6.4,ppg:0.5,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:87,player:'Trevor Etienne',team:'CAR',pts:11.7,ppg:0.7,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:88,player:'Seth McGowan',team:'IND',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:89,player:'Kendre Miller',team:'NO',pts:33.3,ppg:4.8,projPts:0.0,projPpg:0.0},
  {pos:'RB',rank:90,player:'Jawhar Jordan',team:'HOU',pts:29.7,ppg:7.4,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:101,player:'Marvin Mims Jr.',team:'DEN',pts:93.0,ppg:5.8,projPts:0.0,projPpg:0.0},
  {pos:'K',rank:15,player:'Trey Smack',team:'GB',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'K',rank:16,player:'Jake Elliott',team:'PHI',pts:116.0,ppg:6.8,projPts:119.0,projPpg:7.0},
  {pos:'TE',rank:30,player:'Mike Gesicki',team:'CIN',pts:70.7,ppg:5.4,projPts:119.7,projPpg:7.0},
  {pos:'TE',rank:31,player:'Evan Engram',team:'DEN',pts:102.8,ppg:6.4,projPts:124.9,projPpg:7.3},
  {pos:'TE',rank:32,player:'David Njoku',team:'LAC',pts:86.3,ppg:7.2,projPts:117.1,projPpg:6.9},
  {pos:'TE',rank:33,player:'Michael Mayer',team:'LV',pts:73.8,ppg:5.7,projPts:0.0,projPpg:0.0},
  {pos:'TE',rank:34,player:'Jake Tonges',team:'SF',pts:93.3,ppg:5.8,projPts:65.0,projPpg:3.8},
  {pos:'WR',rank:102,player:'KaVontae Turpin',team:'DAL',pts:84.5,ppg:5.6,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:103,player:'Jaylin Lane',team:'WAS',pts:49.2,ppg:3.3,projPts:0.0,projPpg:0.0},
  {pos:'WR',rank:104,player:'Cryus Allen',team:'KC',pts:0.0,ppg:0.0,projPts:0.0,projPpg:0.0},
  {pos:'QB',rank:32,player:'Tua Tagovailoa',team:'ATL',pts:175.6,ppg:12.5,projPts:264.0,projPpg:15.5}
];

// Give every player a stable id (index is fine — PLAYERS is a fixed list).
PLAYERS.forEach((p, i) => { p.id = i; });

const POSITION_ORDER = ['QB', 'RB', 'WR', 'TE', 'K'];

// Sourced from live training-camp coverage (CBS Sports SportsLine model,
// FantasyPros, Yahoo Sports, SI/On SI) as of August 20, 2026.
// Sourced from live training-camp coverage (CBS Sports SportsLine model,
// FantasyPros, Yahoo Sports, NFL.com, ESPN, FanDuel Research, RotoWire,
// RotoBaller, Athlon, ClutchPoints) as of Aug 20, 2026.
const SLEEPERS = [
  // ---- QB ----
  {
    player: 'Jacoby Brissett',
    pos: 'QB', team: 'ARI',
    category: 'Prove-It Starter',
    round: 'Late-round QB2',
    upside: 'Threw for 3,300 yards and 23 TDs in 12 starts last year; now gets a full offseason as QB1 with McBride, Harrison Jr. and Jeremiyah Love',
    risk: 'Journeyman ceiling — hasn\'t sustained a full season as a starter before'
  },
  {
    player: 'Tyler Shough',
    pos: 'QB', team: 'NO',
    category: 'Sophomore Breakout',
    round: 'QB20 ADP, low-end QB2',
    upside: "Kellen Moore's tempo-heavy scheme has a track record of fantasy-friendly QB numbers; explosive rookie speed at receiver around him",
    risk: 'Unproven over a full season as a starter'
  },
  {
    player: 'Kyler Murray',
    pos: 'QB', team: 'MIN',
    category: 'Fresh Start',
    round: 'Named Week 1 starter Aug. 19',
    upside: 'Released by Arizona, signed with Minnesota and beat out J.J. McCarthy for the job; elite rushing floor plus Justin Jefferson as a target',
    risk: 'Landing-spot uncertainty depressed his ADP; missed time last year with a foot injury'
  },
  {
    player: 'Malik Willis',
    pos: 'QB', team: 'MIA',
    category: 'Deep Dart Throw',
    round: 'Deep-league / 2QB only',
    upside: 'Rushing floor alone could make him a streaming option — a shot at the NFL single-season QB rush attempts record isn\'t out of the question',
    risk: 'Miami\'s pass-catching corps is one of the league\'s thinnest'
  },
  // ---- RB ----
  {
    player: 'Jeremiyah Love',
    pos: 'RB', team: 'ARI',
    category: 'Rookie Weapon',
    round: 'No. 4 overall pick',
    upside: 'Joins a Cardinals offense with Trey McBride and a full season of Jacoby Brissett as starter',
    risk: 'Rookie touch-share is never guaranteed even for top picks'
  },
  {
    player: 'Woody Marks',
    pos: 'RB', team: 'HOU',
    category: 'Camp Winner',
    round: 'Value RB2',
    upside: 'Won the Texans\' backfield job outright, pushing veteran Nick Chubb out of the picture entirely by midseason last year',
    risk: 'Houston could still add competition; unproven as a full-time back'
  },
  {
    player: 'Jonathon Brooks',
    pos: 'RB', team: 'CAR',
    category: 'Post-Hype Sleeper',
    round: 'ADP ~125',
    upside: 'Full year removed from a knee injury in a run-heavy Panthers offense',
    risk: 'Suffered two ACL tears in the same knee within 13 months — real injury history to weigh'
  },
  {
    player: 'Jonah Coleman',
    pos: 'RB', team: 'DEN',
    category: 'Depth Chart Climber',
    round: 'Denver\'s RB3',
    upside: 'Could inherit early-down work opposite R.J. Harvey if J.K. Dobbins gets hurt again, which is a real possibility',
    risk: 'Buried on the depth chart unless an injury opens the door'
  },
  {
    player: 'Nicholas Singleton',
    pos: 'RB', team: 'TEN',
    category: 'Deep Sleeper',
    round: 'ADP ~233 / RB62',
    upside: 'Explosive rookie fifth-rounder in a genuinely open Titans backfield — Pollard and Spears both have real question marks',
    risk: 'Currently buried behind three other backs on the depth chart'
  },
  {
    player: 'Emmett Johnson',
    pos: 'RB', team: 'KC',
    category: 'Landing Spot Lottery',
    round: 'Deep-league stash',
    upside: 'Big Ten Running Back of the Year who fell to Round 5 on testing, not talent — the Chiefs landing him is a dream outcome',
    risk: 'Buried on the depth chart behind the incumbent starter for now'
  },
  {
    player: 'Tank Bigsby',
    pos: 'RB', team: 'PHI',
    category: 'Efficiency Bench Piece',
    round: 'Available outside top 150',
    upside: 'Averaged 5.9 yards/carry in a limited Eagles role last year and flashed a 104-yard game — clear RB2 insurance behind Saquon Barkley',
    risk: 'Barkley\'s workload leaves little room unless he\'s limited'
  },
  // ---- WR ----
  {
    player: 'Alec Pierce',
    pos: 'WR', team: 'IND',
    category: 'Volume Riser',
    round: "Colts' new clear-cut WR1",
    upside: 'Led the NFL at 21.3 yards/reception in 2025; signed a big new contract this offseason',
    risk: 'Boom/bust — averaged only 3.1 catches/game; low floor even with big-play ceiling'
  },
  {
    player: 'DeVonta Smith',
    pos: 'WR', team: 'PHI',
    category: 'Post-Trade Value',
    round: 'ADP ~ Round 3',
    upside: 'Inherits the Eagles\' clear WR1 role now that A.J. Brown was sent to New England; hit 1,000 yards even in a bottom-10 passing offense last year',
    risk: 'Philly\'s offensive identity still runs through the ground game'
  },
  {
    player: "De'Zhaun Stribling",
    pos: 'WR', team: 'SF',
    category: 'Rookie Opportunity',
    round: 'Late-round dart throw',
    upside: 'Slots in as SF\'s No. 3 target with Ricky Pearsall out for the year; familiar territory in a Kyle Shanahan offense',
    risk: 'Now sharing snaps with newly-signed veterans Mike Evans and Deebo Samuel Sr., not a clean path to volume'
  },
  {
    player: 'Rome Odunze',
    pos: 'WR', team: 'CHI',
    category: 'Injury Beneficiary',
    round: 'ADP climbing as camp progresses',
    upside: 'Poised for a bump in early-season targets while Luther Burden III (groin) is expected to miss the preseason',
    risk: 'Burden is expected back for Week 1, capping the runway'
  },
  {
    player: 'Jordyn Tyson',
    pos: 'WR', team: 'NO',
    category: 'Rookie Speed',
    round: 'Deep-league dart throw',
    upside: 'Gives New Orleans a legitimate explosive threat if he stays healthy through camp',
    risk: 'Rookie WR volatility, tied to Shough\'s development'
  },
  {
    player: 'Josh Downs',
    pos: 'WR', team: 'IND',
    category: 'Value Pick',
    round: 'Colts No. 2 option',
    upside: 'Reliable slot role behind Alec Pierce in a top-ranked Colts offense',
    risk: 'Dealing with a minor groin issue in camp; ceiling capped by Pierce\'s target share'
  },
  {
    player: 'Tank Dell',
    pos: 'WR', team: 'HOU',
    category: 'Post-Hype Sleeper',
    round: 'ADP ~ Round 15',
    upside: 'Back in full pads and cleared to practice for the first time since injury; explosive YAC threat when healthy',
    risk: 'Long layoff — real injury risk, but the price makes it a low-cost gamble'
  },
  {
    player: 'Stefon Diggs',
    pos: 'WR', team: 'WAS',
    category: 'Fresh Start',
    round: 'ADP still settling',
    upside: 'Caught 85 passes for 1,013 yards with New England last year; now paired with Jayden Daniels after an August signing',
    risk: 'Turns 32 this year, and joining a new offense in August creates early-season uncertainty'
  },
  {
    player: 'Jayden Higgins',
    pos: 'WR', team: 'HOU',
    category: 'Sophomore Riser',
    round: 'Part of the Iowa State duo',
    upside: 'Flashed real talent as a rookie; Houston moved on from Christian Kirk, opening up more target share',
    risk: 'Target competition with Nico Collins, Tank Dell and Jaylin Noel'
  },
  {
    player: 'Jaylin Noel',
    pos: 'WR', team: 'HOU',
    category: 'Sophomore Riser',
    round: 'Part of the Iowa State duo',
    upside: 'Houston\'s revamped offensive line and tempo should create more volume to go around',
    risk: 'Same crowded target competition as Higgins'
  },
  {
    player: 'Emeka Egbuka',
    pos: 'WR', team: 'TB',
    category: 'Vacated Role',
    round: 'Rising fast in August',
    upside: 'With Mike Evans now in San Francisco, the door is wide open for Egbuka to become Tampa Bay\'s top target — a detailed route runner who creates his own separation',
    risk: 'Still needs to prove he can carry a true WR1 workload'
  },
  // ---- TE ----
  {
    player: 'Isaiah Likely',
    pos: 'TE', team: 'NYG',
    category: 'Coaching Reunion',
    round: 'ADP ~ Round 8-9',
    upside: "Followed HC John Harbaugh from Baltimore to New York; building chemistry with Jaxson Dart, no Mark Andrews competing for targets anymore",
    risk: 'Unproven as a true TE1 workload outside Baltimore\'s system'
  },
  {
    player: 'Jake Tonges',
    pos: 'TE', team: 'SF',
    category: 'Injury Handcuff',
    round: 'Late-round streamer/stash',
    upside: 'Direct George Kittle replacement if Kittle opens the year on PUP; caught 5 TDs filling in last season',
    risk: "Value evaporates fast — Kittle is trending toward a Week 1 return"
  },
  {
    player: 'Greg Dulcich',
    pos: 'TE', team: 'MIA',
    category: 'Efficiency Darling',
    round: 'Mostly undrafted',
    upside: 'Ranked top-6 among TEs in targets/route and yards/route run in 2025; Miami\'s receiving corps still lacks a clear high-volume option',
    risk: 'Going undrafted in most leagues for a reason — role still needs to be earned'
  },
  {
    player: 'Chig Okonkwo',
    pos: 'TE', team: 'WAS',
    category: 'Fresh Start',
    round: 'Washington\'s new primary receiving TE',
    upside: '56 catches for 560 yards with Tennessee last year; now paired with Jayden Daniels, who has a track record of fantasy-relevant tight ends',
    risk: 'Stefon Diggs\' arrival in Washington could cut into his target share'
  },
  {
    player: 'Dalton Kincaid',
    pos: 'TE', team: 'BUF',
    category: 'Analytics Darling',
    round: 'Late-round TE1 upside',
    upside: 'His 1.8 yards/route run since 2023 trails only Kittle, McBride and Bowers among qualified tight ends; healthy entering his fourth year',
    risk: 'Buffalo\'s offense has other mouths to feed at receiver'
  },
  {
    player: 'Gunnar Helm',
    pos: 'TE', team: 'TEN',
    category: 'Vacated Role',
    round: 'Deep-league flier',
    upside: "Set a Titans rookie-TE franchise reception record (44 catches) last year; Chig Okonkwo's departure clears the position's receiving hierarchy for him",
    risk: 'Unproven as the clear-cut No. 1 target at the position'
  },
  {
    player: 'Jake Raridon',
    pos: 'TE', team: 'NE',
    category: 'Injury Handcuff',
    round: 'ADP ~ TE44',
    upside: "Josh McDaniels' offenses historically use multiple-TE sets; direct beneficiary if Hunter Henry (age 32) misses time",
    risk: 'Purely matchup/injury-contingent value behind an established starter'
  }
];

// Sourced from live training-camp coverage (FantasyPros, Yahoo Sports,
// Football Nation, ESPN/AJC joint-practice reporting) as of August 20, 2026.
const INJURIES = [
  {
    player: 'Ricky Pearsall',
    pos: 'WR', team: 'SF',
    status: 'Out for Season / PCL Surgery',
    severity: 'out',
    handcuff: "De'Zhaun Stribling",
    handcuffNote: '(SF WR — SF also signed veteran Deebo Samuel Sr. to fill the void)',
    recommendation: 'Off the board for redraft — target the handcuff sleeper instead'
  },
  {
    player: 'George Kittle',
    pos: 'TE', team: 'SF',
    status: 'PUP / Achilles Recovery — trending toward Week 1',
    severity: 'questionable',
    handcuff: 'Jake Tonges',
    handcuffNote: '(SF TE, splits reps with Luke Farrell if Kittle opens on PUP)',
    recommendation: 'Kittle is targeting a Sept. 10 return vs. the Rams — draft as a discounted TE1 with a Week 1-4 contingency plan'
  },
  {
    player: 'Christian McCaffrey',
    pos: 'RB', team: 'SF',
    status: 'Day-to-Day / Calf & Soft-Tissue Tightness',
    severity: 'day-to-day',
    handcuff: 'Isaac Guerendo',
    handcuffNote: '(SF RB, also on PUP but expected back Week 1)',
    recommendation: 'Not a red flag yet, but monitor camp reports closely before draft day'
  },
  {
    player: 'Michael Penix Jr.',
    pos: 'QB', team: 'ATL',
    status: 'Not Yet Cleared for 11-on-11 / ACL Recovery',
    severity: 'out',
    handcuff: 'Tua Tagovailoa',
    handcuffNote: '(ATL QB — leading the job by default, but struggling in camp)',
    recommendation: 'Speculative late-round stash only; ADP has drifted into the 260s while he\'s sidelined'
  },
  {
    player: 'Anthony Richardson',
    pos: 'QB', team: 'IND',
    status: 'Roster Uncertainty — Requested Trade',
    severity: 'questionable',
    handcuff: 'Daniel Jones',
    handcuffNote: "(IND QB, ahead of him — Jones looks 'flawless' returning from his own Achilles tear)",
    recommendation: 'Dynasty stash only if he\'s dealt — not draftable as a Colts backup in redraft'
  },
  {
    player: 'Malik Nabers',
    pos: 'WR', team: 'NYG',
    status: 'Recovering from ACL Tear — trending well',
    severity: 'questionable',
    handcuff: "Wan'Dale Robinson",
    handcuffNote: '(NYG WR, next in line for target share if Nabers is limited)',
    recommendation: 'Nabers is back practicing and on track for Week 1 — a discount worth buying if his ADP hasn\'t corrected yet'
  }
];

const SLEEPER_NAMES = new Set(SLEEPERS.map(s => s.player));

function findPlayerByName(name) {
  return PLAYERS.find(p => p.player === name) || null;
}
