// ============================================================
// Shared data for the draft tracker. Every page loads this file
// so player info only lives in one place.
// ============================================================

const PLAYERS = [
  {pos:'RB',rank:1,player:'Jahmyr Gibbs',team:'DET',pts:428.9,ppg:25.2},
  {pos:'RB',rank:2,player:'Bijan Robinson',team:'ATL',pts:427.9,ppg:25.2},
  {pos:'WR',rank:1,player:'Ja\'Marr Chase',team:'CIN',pts:426.9,ppg:25.1},
  {pos:'WR',rank:2,player:'Puka Nacua',team:'LAR',pts:425.8,ppg:25.0},
  {pos:'RB',rank:3,player:'Christian McCaffrey',team:'SF',pts:424.8,ppg:25.0},
  {pos:'WR',rank:3,player:'Amon-Ra St. Brown',team:'DET',pts:423.7,ppg:24.9},
  {pos:'WR',rank:4,player:'Jaxon Smith-Njigba',team:'SEA',pts:422.6,ppg:24.9},
  {pos:'RB',rank:4,player:'Jonathan Taylor',team:'IND',pts:421.6,ppg:24.8},
  {pos:'WR',rank:5,player:'CeeDee Lamb',team:'DAL',pts:420.6,ppg:24.7},
  {pos:'RB',rank:5,player:'Chase Brown',team:'CIN',pts:419.5,ppg:24.7},
  {pos:'RB',rank:6,player:'James Cook III',team:'BUF',pts:418.4,ppg:24.6},
  {pos:'RB',rank:7,player:'De\'Von Achane',team:'MIA',pts:417.4,ppg:24.6},
  {pos:'WR',rank:6,player:'Justin Jefferson',team:'MIN',pts:416.4,ppg:24.5},
  {pos:'RB',rank:8,player:'Kenneth Walker III',team:'KC',pts:415.3,ppg:24.4},
  {pos:'RB',rank:9,player:'Ashton Jeanty',team:'LV',pts:414.2,ppg:24.4},
  {pos:'RB',rank:10,player:'Omarion Hampton',team:'LAC',pts:413.2,ppg:24.3},
  {pos:'WR',rank:7,player:'Drake London',team:'ATL',pts:412.1,ppg:24.2},
  {pos:'RB',rank:11,player:'Saquon Barkley',team:'PHI',pts:411.1,ppg:24.2},
  {pos:'TE',rank:1,player:'Brock Bowers',team:'LV',pts:410.1,ppg:24.1},
  {pos:'RB',rank:12,player:'Derrick Henry',team:'BAL',pts:409.0,ppg:24.1},
  {pos:'RB',rank:13,player:'Jeremiyah Love',team:'ARI',pts:407.9,ppg:24.0},
  {pos:'TE',rank:2,player:'Trey McBride',team:'ARI',pts:406.9,ppg:23.9},
  {pos:'RB',rank:14,player:'Kyren Williams',team:'LAR',pts:405.9,ppg:23.9},
  {pos:'WR',rank:8,player:'Nico Collins',team:'HOU',pts:404.8,ppg:23.8},
  {pos:'WR',rank:9,player:'A.J. Brown',team:'NE',pts:403.8,ppg:23.8},
  {pos:'WR',rank:10,player:'Malik Nabers',team:'NYG',pts:402.7,ppg:23.7},
  {pos:'WR',rank:11,player:'Rashee Rice',team:'KC',pts:401.6,ppg:23.6},
  {pos:'WR',rank:12,player:'DeVonta Smith',team:'PHI',pts:400.6,ppg:23.6},
  {pos:'WR',rank:13,player:'George Pickens',team:'DAL',pts:399.6,ppg:23.5},
  {pos:'RB',rank:15,player:'Josh Jacobs',team:'GB',pts:398.5,ppg:23.4},
  {pos:'WR',rank:14,player:'Chris Olave',team:'NO',pts:397.4,ppg:23.4},
  {pos:'WR',rank:15,player:'Zay Flowers',team:'BAL',pts:396.4,ppg:23.3},
  {pos:'RB',rank:16,player:'Breece Hall',team:'NYJ',pts:395.4,ppg:23.3},
  {pos:'RB',rank:17,player:'Javonte Williams',team:'DAL',pts:394.3,ppg:23.2},
  {pos:'WR',rank:16,player:'Garrett Wilson',team:'NYJ',pts:393.2,ppg:23.1},
  {pos:'WR',rank:17,player:'Tetairoa McMillan',team:'CAR',pts:392.2,ppg:23.1},
  {pos:'QB',rank:1,player:'Josh Allen',team:'BUF',pts:391.1,ppg:23.0},
  {pos:'WR',rank:18,player:'Jaylen Waddle',team:'DEN',pts:390.1,ppg:22.9},
  {pos:'WR',rank:19,player:'Emeka Egbuka',team:'TB',pts:389.1,ppg:22.9},
  {pos:'RB',rank:18,player:'Bucky Irving',team:'TB',pts:388.0,ppg:22.8},
  {pos:'WR',rank:20,player:'Tee Higgins',team:'CIN',pts:386.9,ppg:22.8},
  {pos:'WR',rank:21,player:'Ladd McConkey',team:'LAC',pts:385.9,ppg:22.7},
  {pos:'TE',rank:3,player:'Tyler Warren',team:'IND',pts:384.9,ppg:22.6},
  {pos:'TE',rank:4,player:'Colston Loveland',team:'CHI',pts:383.8,ppg:22.6},
  {pos:'WR',rank:22,player:'Luther Burden III',team:'CHI',pts:382.8,ppg:22.5},
  {pos:'RB',rank:19,player:'Travis Etienne Jr.',team:'NO',pts:381.7,ppg:22.5},
  {pos:'WR',rank:23,player:'Rome Odunze',team:'CHI',pts:380.6,ppg:22.4},
  {pos:'WR',rank:24,player:'Terry McLaurin',team:'WAS',pts:379.6,ppg:22.3},
  {pos:'WR',rank:25,player:'Carnell Tate',team:'TEN',pts:378.6,ppg:22.3},
  {pos:'QB',rank:2,player:'Lamar Jackson',team:'BAL',pts:377.5,ppg:22.2},
  {pos:'QB',rank:3,player:'Jayden Daniels',team:'WAS',pts:376.4,ppg:22.1},
  {pos:'RB',rank:20,player:'Cam Skattebo',team:'NYG',pts:375.4,ppg:22.1},
  {pos:'RB',rank:21,player:'Quinshon Judkins',team:'CLE',pts:374.4,ppg:22.0},
  {pos:'WR',rank:26,player:'DJ Moore',team:'BUF',pts:373.3,ppg:22.0},
  {pos:'QB',rank:4,player:'Drake Maye',team:'NE',pts:372.2,ppg:21.9},
  {pos:'QB',rank:5,player:'Jalen Hurts',team:'PHI',pts:371.2,ppg:21.8},
  {pos:'WR',rank:27,player:'Mike Evans',team:'SF',pts:370.1,ppg:21.8},
  {pos:'RB',rank:22,player:'TreVeyon Henderson',team:'NE',pts:369.1,ppg:21.7},
  {pos:'WR',rank:28,player:'Davante Adams',team:'LAR',pts:368.1,ppg:21.7},
  {pos:'RB',rank:23,player:'Bhayshul Tuten',team:'JAC',pts:367.0,ppg:21.6},
  {pos:'RB',rank:24,player:'D\'Andre Swift',team:'CHI',pts:365.9,ppg:21.5},
  {pos:'WR',rank:29,player:'Christian Watson',team:'GB',pts:364.9,ppg:21.5},
  {pos:'WR',rank:30,player:'Parker Washington',team:'JAC',pts:363.9,ppg:21.4},
  {pos:'WR',rank:31,player:'Jameson Williams',team:'DET',pts:362.8,ppg:21.3},
  {pos:'RB',rank:25,player:'David Montgomery',team:'HOU',pts:361.8,ppg:21.3},
  {pos:'RB',rank:26,player:'Jadarian Price',team:'SEA',pts:360.7,ppg:21.2},
  {pos:'RB',rank:27,player:'Tony Pollard',team:'TEN',pts:359.6,ppg:21.2},
  {pos:'TE',rank:5,player:'Kyle Pitts Sr.',team:'ATL',pts:358.6,ppg:21.1},
  {pos:'TE',rank:6,player:'Sam LaPorta',team:'DET',pts:357.6,ppg:21.0},
  {pos:'WR',rank:32,player:'Michael Pittman Jr.',team:'PIT',pts:356.5,ppg:21.0},
  {pos:'WR',rank:33,player:'Marvin Harrison Jr.',team:'ARI',pts:355.4,ppg:20.9},
  {pos:'TE',rank:7,player:'Harold Fannin Jr.',team:'CLE',pts:354.4,ppg:20.8},
  {pos:'WR',rank:34,player:'DK Metcalf',team:'PIT',pts:353.4,ppg:20.8},
  {pos:'QB',rank:6,player:'Joe Burrow',team:'CIN',pts:352.3,ppg:20.7},
  {pos:'QB',rank:7,player:'Jaxson Dart',team:'NYG',pts:351.2,ppg:20.7},
  {pos:'WR',rank:35,player:'Courtland Sutton',team:'DEN',pts:350.2,ppg:20.6},
  {pos:'WR',rank:36,player:'Michael Wilson',team:'ARI',pts:349.1,ppg:20.5},
  {pos:'QB',rank:8,player:'Trevor Lawrence',team:'JAC',pts:348.1,ppg:20.5},
  {pos:'RB',rank:28,player:'Rhamondre Stevenson',team:'NE',pts:347.1,ppg:20.4},
  {pos:'RB',rank:29,player:'Jonathon Brooks',team:'CAR',pts:346.0,ppg:20.4},
  {pos:'QB',rank:9,player:'Caleb Williams',team:'CHI',pts:344.9,ppg:20.3},
  {pos:'QB',rank:10,player:'Dak Prescott',team:'DAL',pts:343.9,ppg:20.2},
  {pos:'QB',rank:11,player:'Bo Nix',team:'DEN',pts:342.9,ppg:20.2},
  {pos:'WR',rank:37,player:'Josh Downs',team:'IND',pts:341.8,ppg:20.1},
  {pos:'QB',rank:12,player:'Brock Purdy',team:'SF',pts:340.8,ppg:20.0},
  {pos:'QB',rank:13,player:'Matthew Stafford',team:'LAR',pts:339.7,ppg:20.0},
  {pos:'WR',rank:38,player:'Matthew Golden',team:'GB',pts:338.6,ppg:19.9},
  {pos:'WR',rank:39,player:'Brian Thomas Jr.',team:'JAC',pts:337.6,ppg:19.9},
  {pos:'QB',rank:14,player:'Justin Herbert',team:'LAC',pts:336.6,ppg:19.8},
  {pos:'WR',rank:40,player:'Jakobi Meyers',team:'JAC',pts:335.5,ppg:19.7},
  {pos:'WR',rank:41,player:'Wan\'Dale Robinson',team:'TEN',pts:334.4,ppg:19.7},
  {pos:'WR',rank:42,player:'Jordan Addison',team:'MIN',pts:333.4,ppg:19.6},
  {pos:'WR',rank:43,player:'Alec Pierce',team:'IND',pts:332.4,ppg:19.6},
  {pos:'WR',rank:44,player:'Makai Lemon',team:'PHI',pts:331.3,ppg:19.5},
  {pos:'QB',rank:15,player:'Patrick Mahomes',team:'KC',pts:330.2,ppg:19.4},
  {pos:'RB',rank:30,player:'Jaylen Warren',team:'PIT',pts:329.2,ppg:19.4},
  {pos:'RB',rank:31,player:'J.K. Dobbins',team:'DEN',pts:328.1,ppg:19.3},
  {pos:'RB',rank:32,player:'Kenny Gainwell',team:'TB',pts:327.1,ppg:19.2},
  {pos:'RB',rank:33,player:'Rico Dowdle',team:'PIT',pts:326.1,ppg:19.2},
  {pos:'TE',rank:8,player:'George Kittle',team:'SF',pts:325.0,ppg:19.1},
  {pos:'RB',rank:34,player:'Chuba Hubbard',team:'CAR',pts:323.9,ppg:19.1},
  {pos:'RB',rank:35,player:'Rachaad White',team:'WAS',pts:322.9,ppg:19.0},
  {pos:'TE',rank:9,player:'Tucker Kraft',team:'GB',pts:321.9,ppg:18.9},
  {pos:'TE',rank:10,player:'Dallas Goedert',team:'PHI',pts:320.8,ppg:18.9},
  {pos:'TE',rank:11,player:'Travis Kelce',team:'KC',pts:319.8,ppg:18.8},
  {pos:'RB',rank:36,player:'RJ Harvey',team:'DEN',pts:318.7,ppg:18.7},
  {pos:'RB',rank:37,player:'Blake Corum',team:'LAR',pts:317.6,ppg:18.7},
  {pos:'QB',rank:16,player:'Kyler Murray',team:'MIN',pts:316.6,ppg:18.6},
  {pos:'WR',rank:45,player:'Jayden Reed',team:'GB',pts:315.6,ppg:18.6},
  {pos:'TE',rank:12,player:'Dalton Kincaid',team:'BUF',pts:314.5,ppg:18.5},
  {pos:'TE',rank:13,player:'Jake Ferguson',team:'DAL',pts:313.4,ppg:18.4},
  {pos:'TE',rank:14,player:'Mark Andrews',team:'BAL',pts:312.4,ppg:18.4},
  {pos:'TE',rank:15,player:'T.J. Hockenson',team:'MIN',pts:311.4,ppg:18.3},
  {pos:'RB',rank:38,player:'Aaron Jones Sr.',team:'MIN',pts:310.3,ppg:18.3},
  {pos:'WR',rank:46,player:'Jordyn Tyson',team:'NO',pts:309.2,ppg:18.2},
  {pos:'WR',rank:47,player:'KC Concepcion',team:'CLE',pts:308.2,ppg:18.1},
  {pos:'RB',rank:39,player:'Jacory Croskey-Merritt',team:'WAS',pts:307.1,ppg:18.1},
  {pos:'WR',rank:48,player:'Xavier Worthy',team:'KC',pts:306.1,ppg:18.0},
  {pos:'TE',rank:16,player:'Kenyon Sadiq',team:'NYJ',pts:305.1,ppg:17.9},
  {pos:'TE',rank:17,player:'Isaiah Likely',team:'NYG',pts:304.0,ppg:17.9},
  {pos:'WR',rank:49,player:'Jalen Coker',team:'CAR',pts:302.9,ppg:17.8},
  {pos:'WR',rank:50,player:'Quentin Johnston',team:'LAC',pts:301.9,ppg:17.8},
  {pos:'WR',rank:51,player:'Romeo Doubs',team:'NE',pts:300.9,ppg:17.7},
  {pos:'WR',rank:52,player:'Stefon Diggs',team:'WAS',pts:299.8,ppg:17.6},
  {pos:'TE',rank:18,player:'Hunter Henry',team:'NE',pts:298.8,ppg:17.6},
  {pos:'RB',rank:40,player:'Kyle Monangai',team:'CHI',pts:297.7,ppg:17.5},
  {pos:'QB',rank:17,player:'Tyler Shough',team:'NO',pts:296.6,ppg:17.4},
  {pos:'WR',rank:53,player:'Deebo Samuel Sr.',team:'SF',pts:295.6,ppg:17.4},
  {pos:'RB',rank:41,player:'Woody Marks',team:'HOU',pts:294.5,ppg:17.3},
  {pos:'RB',rank:42,player:'Zach Charbonnet',team:'SEA',pts:293.5,ppg:17.3},
  {pos:'WR',rank:54,player:'Khalil Shakir',team:'BUF',pts:292.4,ppg:17.2},
  {pos:'RB',rank:43,player:'Tank Bigsby',team:'PHI',pts:291.4,ppg:17.1},
  {pos:'WR',rank:55,player:'Chris Godwin Jr.',team:'TB',pts:290.4,ppg:17.1},
  {pos:'WR',rank:56,player:'Jerry Jeudy',team:'CLE',pts:289.3,ppg:17.0},
  {pos:'QB',rank:18,player:'Jared Goff',team:'DET',pts:288.2,ppg:17.0},
  {pos:'RB',rank:44,player:'Jordan Mason',team:'MIN',pts:287.2,ppg:16.9},
  {pos:'QB',rank:19,player:'Daniel Jones',team:'IND',pts:286.1,ppg:16.8},
  {pos:'WR',rank:57,player:'Rashid Shaheed',team:'SEA',pts:285.1,ppg:16.8},
  {pos:'RB',rank:45,player:'Alvin Kamara',team:'NO',pts:284.0,ppg:16.7},
  {pos:'RB',rank:46,player:'Chris Rodriguez Jr.',team:'JAC',pts:283.0,ppg:16.6},
  {pos:'RB',rank:47,player:'Brian Robinson Jr.',team:'ATL',pts:281.9,ppg:16.6},
  {pos:'QB',rank:20,player:'Baker Mayfield',team:'TB',pts:280.9,ppg:16.5},
  {pos:'RB',rank:48,player:'Isiah Pacheco',team:'DET',pts:279.9,ppg:16.5},
  {pos:'QB',rank:21,player:'Malik Willis',team:'MIA',pts:278.8,ppg:16.4},
  {pos:'WR',rank:58,player:'De\'Zhaun Stribling',team:'SF',pts:277.8,ppg:16.3},
  {pos:'WR',rank:59,player:'Jalen McMillan',team:'TB',pts:276.7,ppg:16.3},
  {pos:'WR',rank:60,player:'Calvin Ridley',team:'TEN',pts:275.6,ppg:16.2},
  {pos:'WR',rank:61,player:'Denzel Boston',team:'CLE',pts:274.6,ppg:16.2},
  {pos:'WR',rank:62,player:'Travis Hunter',team:'JAC',pts:273.5,ppg:16.1},
  {pos:'WR',rank:63,player:'Adonai Mitchell',team:'NYJ',pts:272.5,ppg:16.0},
  {pos:'WR',rank:64,player:'Germie Bernard',team:'PIT',pts:271.4,ppg:16.0},
  {pos:'WR',rank:65,player:'Jalen Nailor',team:'LV',pts:270.4,ppg:15.9},
  {pos:'WR',rank:66,player:'Tre Tucker',team:'LV',pts:269.4,ppg:15.8},
  {pos:'RB',rank:49,player:'Ray Davis',team:'BUF',pts:268.3,ppg:15.8},
  {pos:'RB',rank:50,player:'Tyrone Tracy Jr.',team:'NYG',pts:267.2,ppg:15.7},
  {pos:'RB',rank:51,player:'Mike Washington Jr.',team:'LV',pts:266.2,ppg:15.7},
  {pos:'TE',rank:19,player:'Juwan Johnson',team:'NO',pts:265.1,ppg:15.6},
  {pos:'RB',rank:52,player:'Tyler Allgeier',team:'ARI',pts:264.1,ppg:15.5},
  {pos:'RB',rank:53,player:'Keaton Mitchell',team:'LAC',pts:263.0,ppg:15.5},
  {pos:'RB',rank:54,player:'Dylan Sampson',team:'CLE',pts:262.0,ppg:15.4},
  {pos:'TE',rank:20,player:'Terrance Ferguson',team:'LAR',pts:260.9,ppg:15.3},
  {pos:'WR',rank:67,player:'Omar Cooper Jr.',team:'NYJ',pts:259.9,ppg:15.3},
  {pos:'WR',rank:68,player:'Rashod Bateman',team:'BAL',pts:258.9,ppg:15.2},
  {pos:'WR',rank:69,player:'Jauan Jennings',team:'MIN',pts:257.8,ppg:15.2},
  {pos:'WR',rank:70,player:'Tank Dell',team:'HOU',pts:256.8,ppg:15.1},
  {pos:'RB',rank:55,player:'Tyjae Spears',team:'TEN',pts:255.7,ppg:15.0},
  {pos:'QB',rank:22,player:'Jordan Love',team:'GB',pts:254.7,ppg:15.0},
  {pos:'RB',rank:56,player:'Braelon Allen',team:'NYJ',pts:253.6,ppg:14.9},
  {pos:'K',rank:1,player:'Brandon Aubrey',team:'DAL',pts:239.9,ppg:14.1},
  {pos:'K',rank:2,player:'Cameron Dicker',team:'LAC',pts:238.9,ppg:14.1},
  {pos:'K',rank:3,player:'Jason Myers',team:'SEA',pts:237.8,ppg:14.0},
  {pos:'K',rank:4,player:'Harrison Mevis',team:'LAR',pts:236.8,ppg:13.9},
  {pos:'K',rank:5,player:'Ka\'imi Fairbairn',team:'HOU',pts:235.8,ppg:13.9},
  {pos:'K',rank:6,player:'Eddy Pineiro',team:'SF',pts:234.7,ppg:13.8},
  {pos:'K',rank:7,player:'Harrison Butker',team:'KC',pts:233.7,ppg:13.7},
  {pos:'K',rank:8,player:'Cam Little',team:'JAC',pts:232.6,ppg:13.7},
  {pos:'K',rank:9,player:'Jake Bates',team:'DET',pts:231.5,ppg:13.6},
  {pos:'K',rank:10,player:'Tyler Loop',team:'BAL',pts:230.5,ppg:13.6},
  {pos:'K',rank:11,player:'Cairo Santos',team:'CHI',pts:229.4,ppg:13.5},
  {pos:'K',rank:12,player:'Will Reichard',team:'MIN',pts:228.4,ppg:13.4},
  {pos:'RB',rank:57,player:'Jordan James',team:'SF',pts:227.3,ppg:13.4},
  {pos:'TE',rank:21,player:'Brenton Strange',team:'JAC',pts:226.3,ppg:13.3},
  {pos:'RB',rank:58,player:'James Conner',team:'ARI',pts:225.2,ppg:13.2},
  {pos:'RB',rank:59,player:'Justice Hill',team:'BAL',pts:224.2,ppg:13.2},
  {pos:'WR',rank:71,player:'Zachariah Branch',team:'ATL',pts:223.1,ppg:13.1},
  {pos:'QB',rank:23,player:'Cam Ward',team:'TEN',pts:222.1,ppg:13.1},
  {pos:'QB',rank:24,player:'C.J. Stroud',team:'HOU',pts:221.0,ppg:13.0},
  {pos:'WR',rank:72,player:'Darnell Mooney',team:'NYG',pts:220.0,ppg:12.9},
  {pos:'WR',rank:73,player:'Tre Harris',team:'LAC',pts:218.9,ppg:12.9},
  {pos:'WR',rank:74,player:'Ryan Flournoy',team:'DAL',pts:217.9,ppg:12.8},
  {pos:'WR',rank:75,player:'Antonio Williams',team:'WAS',pts:216.8,ppg:12.8},
  {pos:'WR',rank:76,player:'Jaylin Noel',team:'HOU',pts:215.8,ppg:12.7},
  {pos:'TE',rank:22,player:'Pat Freiermuth',team:'PIT',pts:214.8,ppg:12.6},
  {pos:'TE',rank:23,player:'Dalton Schultz',team:'HOU',pts:213.7,ppg:12.6},
  {pos:'WR',rank:77,player:'Xavier Legette',team:'CAR',pts:212.6,ppg:12.5},
  {pos:'WR',rank:78,player:'Jack Bech',team:'LV',pts:211.6,ppg:12.4},
  {pos:'WR',rank:79,player:'Isaac TeSlaa',team:'DET',pts:210.5,ppg:12.4},
  {pos:'WR',rank:80,player:'Chris Bell',team:'MIA',pts:209.5,ppg:12.3},
  {pos:'TE',rank:24,player:'Chig Okonkwo',team:'WAS',pts:208.4,ppg:12.3},
  {pos:'RB',rank:60,player:'Jonah Coleman',team:'DEN',pts:207.4,ppg:12.2},
  {pos:'RB',rank:61,player:'Kaelon Black',team:'SF',pts:206.3,ppg:12.1},
  {pos:'RB',rank:62,player:'Kaytron Allen',team:'WAS',pts:205.3,ppg:12.1},
  {pos:'TE',rank:25,player:'Gunnar Helm',team:'TEN',pts:204.2,ppg:12.0},
  {pos:'RB',rank:63,player:'Kimani Vidal',team:'LAC',pts:203.2,ppg:12.0},
  {pos:'TE',rank:26,player:'AJ Barner',team:'SEA',pts:202.1,ppg:11.9},
  {pos:'QB',rank:25,player:'Sam Darnold',team:'SEA',pts:201.1,ppg:11.8},
  {pos:'QB',rank:26,player:'Bryce Young',team:'CAR',pts:200.0,ppg:11.8},
  {pos:'QB',rank:27,player:'Fernando Mendoza',team:'LV',pts:199.0,ppg:11.7},
  {pos:'RB',rank:64,player:'Nicholas Singleton',team:'TEN',pts:197.9,ppg:11.6},
  {pos:'RB',rank:65,player:'Demond Claiborne',team:'MIN',pts:196.9,ppg:11.6},
  {pos:'WR',rank:81,player:'Malik Washington',team:'MIA',pts:195.8,ppg:11.5},
  {pos:'RB',rank:66,player:'Jaylen Wright',team:'MIA',pts:194.8,ppg:11.5},
  {pos:'RB',rank:67,player:'Ollie Gordon II',team:'MIA',pts:193.8,ppg:11.4},
  {pos:'WR',rank:82,player:'Jalen Tolbert',team:'MIA',pts:192.7,ppg:11.3},
  {pos:'WR',rank:83,player:'Cooper Kupp',team:'SEA',pts:191.6,ppg:11.3},
  {pos:'WR',rank:84,player:'Caleb Douglas',team:'MIA',pts:190.6,ppg:11.2},
  {pos:'WR',rank:85,player:'Kayshon Boutte',team:'NE',pts:189.5,ppg:11.1},
  {pos:'WR',rank:86,player:'Keenan Allen',team:'IND',pts:188.5,ppg:11.1},
  {pos:'WR',rank:87,player:'Ja\'Kobi Lane',team:'BAL',pts:187.4,ppg:11.0},
  {pos:'WR',rank:88,player:'Ted Hurst',team:'TB',pts:186.4,ppg:11.0},
  {pos:'WR',rank:89,player:'Keon Coleman',team:'BUF',pts:185.3,ppg:10.9},
  {pos:'RB',rank:68,player:'Adam Randall',team:'BAL',pts:180.1,ppg:10.6},
  {pos:'RB',rank:69,player:'Samaje Perine',team:'CIN',pts:179.0,ppg:10.5},
  {pos:'RB',rank:70,player:'LeQuint Allen',team:'JAC',pts:178.0,ppg:10.5},
  {pos:'RB',rank:71,player:'MarShawn Lloyd',team:'GB',pts:176.9,ppg:10.4},
  {pos:'RB',rank:72,player:'Jaydon Blue',team:'DAL',pts:175.9,ppg:10.3},
  {pos:'RB',rank:73,player:'George Holani',team:'SEA',pts:174.8,ppg:10.3},
  {pos:'RB',rank:74,player:'Ty Johnson',team:'BUF',pts:173.8,ppg:10.2},
  {pos:'RB',rank:75,player:'Emari Demercado',team:'KC',pts:172.8,ppg:10.2},
  {pos:'RB',rank:76,player:'Isaiah Davis',team:'NYJ',pts:171.7,ppg:10.1},
  {pos:'RB',rank:77,player:'Emmett Johnson',team:'KC',pts:170.6,ppg:10.0},
  {pos:'RB',rank:78,player:'Chris Brooks',team:'GB',pts:169.6,ppg:10.0},
  {pos:'RB',rank:79,player:'Sean Tucker',team:'TB',pts:168.6,ppg:9.9},
  {pos:'RB',rank:80,player:'DJ Giddens',team:'IND',pts:167.5,ppg:9.9},
  {pos:'WR',rank:90,player:'Dontayvion Wicks',team:'PHI',pts:166.4,ppg:9.8},
  {pos:'WR',rank:91,player:'Savion Williams',team:'GB',pts:165.4,ppg:9.7},
  {pos:'K',rank:13,player:'Evan McPherson',team:'CIN',pts:162.2,ppg:9.5},
  {pos:'K',rank:14,player:'Nick Folk',team:'ATL',pts:161.2,ppg:9.5},
  {pos:'TE',rank:27,player:'Oronde Gadsden',team:'LAC',pts:160.1,ppg:9.4},
  {pos:'TE',rank:28,player:'Greg Dulcich',team:'MIA',pts:159.1,ppg:9.4},
  {pos:'TE',rank:29,player:'Cade Otton',team:'TB',pts:158.1,ppg:9.3},
  {pos:'WR',rank:92,player:'Pat Bryant',team:'DEN',pts:157.0,ppg:9.2},
  {pos:'WR',rank:93,player:'Tory Horton',team:'SEA',pts:155.9,ppg:9.2},
  {pos:'WR',rank:94,player:'Elijah Sarratt',team:'BAL',pts:154.9,ppg:9.1},
  {pos:'WR',rank:95,player:'Dyami Brown',team:'WAS',pts:153.8,ppg:9.0},
  {pos:'RB',rank:81,player:'Malik Davis',team:'DAL',pts:152.8,ppg:9.0},
  {pos:'RB',rank:82,player:'Emanuel Wilson',team:'SEA',pts:151.8,ppg:8.9},
  {pos:'QB',rank:28,player:'Geno Smith',team:'NYJ',pts:150.7,ppg:8.9},
  {pos:'QB',rank:29,player:'Aaron Rodgers',team:'PIT',pts:149.6,ppg:8.8},
  {pos:'QB',rank:30,player:'Jacoby Brissett',team:'ARI',pts:148.6,ppg:8.7},
  {pos:'QB',rank:31,player:'Deshaun Watson',team:'CLE',pts:147.6,ppg:8.7},
  {pos:'WR',rank:96,player:'Darius Slayton',team:'NYG',pts:146.5,ppg:8.6},
  {pos:'WR',rank:97,player:'Treylon Burks',team:'WAS',pts:145.4,ppg:8.6},
  {pos:'WR',rank:98,player:'Tyquan Thornton',team:'KC',pts:144.4,ppg:8.5},
  {pos:'WR',rank:99,player:'Andrei Iosivas',team:'CIN',pts:143.3,ppg:8.4},
  {pos:'WR',rank:100,player:'Jahan Dotson',team:'ATL',pts:142.3,ppg:8.4},
  {pos:'RB',rank:83,player:'Will Shipley',team:'PHI',pts:141.2,ppg:8.3},
  {pos:'RB',rank:84,player:'Devin Singletary',team:'NYG',pts:140.2,ppg:8.2},
  {pos:'RB',rank:85,player:'Tyler Badie',team:'DEN',pts:139.1,ppg:8.2},
  {pos:'RB',rank:86,player:'Tahj Brooks',team:'CIN',pts:138.1,ppg:8.1},
  {pos:'RB',rank:87,player:'Trevor Etienne',team:'CAR',pts:137.1,ppg:8.1},
  {pos:'RB',rank:88,player:'Seth McGowan',team:'IND',pts:136.0,ppg:8.0},
  {pos:'RB',rank:89,player:'Kendre Miller',team:'NO',pts:134.9,ppg:7.9},
  {pos:'RB',rank:90,player:'Jawhar Jordan',team:'HOU',pts:133.9,ppg:7.9},
  {pos:'WR',rank:101,player:'Marvin Mims Jr.',team:'DEN',pts:132.8,ppg:7.8},
  {pos:'K',rank:15,player:'Trey Smack',team:'GB',pts:129.7,ppg:7.6},
  {pos:'K',rank:16,player:'Jake Elliott',team:'PHI',pts:128.6,ppg:7.6},
  {pos:'TE',rank:30,player:'Mike Gesicki',team:'CIN',pts:127.6,ppg:7.5},
  {pos:'TE',rank:31,player:'Evan Engram',team:'DEN',pts:126.6,ppg:7.4},
  {pos:'TE',rank:32,player:'David Njoku',team:'LAC',pts:125.5,ppg:7.4},
  {pos:'TE',rank:33,player:'Michael Mayer',team:'LV',pts:124.4,ppg:7.3},
  {pos:'TE',rank:34,player:'Jake Tonges',team:'SF',pts:123.4,ppg:7.3},
  {pos:'WR',rank:102,player:'KaVontae Turpin',team:'DAL',pts:122.3,ppg:7.2},
  {pos:'WR',rank:103,player:'Jaylin Lane',team:'WAS',pts:121.3,ppg:7.1},
  {pos:'WR',rank:104,player:'Cryus Allen',team:'KC',pts:120.2,ppg:7.1},
  {pos:'QB',rank:32,player:'Tua Tagovailoa',team:'ATL',pts:119.2,ppg:7.0}
];

// Give every player a stable id (index is fine — PLAYERS is a fixed list).
PLAYERS.forEach((p, i) => { p.id = i; });

const POSITION_ORDER = ['QB', 'RB', 'WR', 'TE', 'K'];

// Sourced from live training-camp coverage (CBS Sports SportsLine model,
// FantasyPros, Yahoo Sports, SI/On SI) as of August 20, 2026.
// Sourced from live training-camp coverage (CBS Sports SportsLine model,
// FantasyPros, Yahoo Sports, NFL.com, ESPN, FanDuel Research, RotoWire,
// RotoBaller, Athlon, ClutchPoints) as of Aug 20, 2026.
const SLEEPERS = [
  // ---- QB ----
  {
    player: 'Jacoby Brissett',
    pos: 'QB', team: 'ARI',
    category: 'Prove-It Starter',
    round: 'Late-round QB2',
    upside: 'Threw for 3,300 yards and 23 TDs in 12 starts last year; now gets a full offseason as QB1 with McBride, Harrison Jr. and Jeremiyah Love',
    risk: 'Journeyman ceiling — hasn\'t sustained a full season as a starter before'
  },
  {
    player: 'Tyler Shough',
    pos: 'QB', team: 'NO',
    category: 'Sophomore Breakout',
    round: 'QB20 ADP, low-end QB2',
    upside: "Kellen Moore's tempo-heavy scheme has a track record of fantasy-friendly QB numbers; explosive rookie speed at receiver around him",
    risk: 'Unproven over a full season as a starter'
  },
  {
    player: 'Kyler Murray',
    pos: 'QB', team: 'MIN',
    category: 'Fresh Start',
    round: 'Named Week 1 starter Aug. 19',
    upside: 'Released by Arizona, signed with Minnesota and beat out J.J. McCarthy for the job; elite rushing floor plus Justin Jefferson as a target',
    risk: 'Landing-spot uncertainty depressed his ADP; missed time last year with a foot injury'
  },
  {
    player: 'Malik Willis',
    pos: 'QB', team: 'MIA',
    category: 'Deep Dart Throw',
    round: 'Deep-league / 2QB only',
    upside: 'Rushing floor alone could make him a streaming option — a shot at the NFL single-season QB rush attempts record isn\'t out of the question',
    risk: 'Miami\'s pass-catching corps is one of the league\'s thinnest'
  },
  // ---- RB ----
  {
    player: 'Jeremiyah Love',
    pos: 'RB', team: 'ARI',
    category: 'Rookie Weapon',
    round: 'No. 4 overall pick',
    upside: 'Joins a Cardinals offense with Trey McBride and a full season of Jacoby Brissett as starter',
    risk: 'Rookie touch-share is never guaranteed even for top picks'
  },
  {
    player: 'Woody Marks',
    pos: 'RB', team: 'HOU',
    category: 'Camp Winner',
    round: 'Value RB2',
    upside: 'Won the Texans\' backfield job outright, pushing veteran Nick Chubb out of the picture entirely by midseason last year',
    risk: 'Houston could still add competition; unproven as a full-time back'
  },
  {
    player: 'Jonathon Brooks',
    pos: 'RB', team: 'CAR',
    category: 'Post-Hype Sleeper',
    round: 'ADP ~125',
    upside: 'Full year removed from a knee injury in a run-heavy Panthers offense',
    risk: 'Suffered two ACL tears in the same knee within 13 months — real injury history to weigh'
  },
  {
    player: 'Jonah Coleman',
    pos: 'RB', team: 'DEN',
    category: 'Depth Chart Climber',
    round: 'Denver\'s RB3',
    upside: 'Could inherit early-down work opposite R.J. Harvey if J.K. Dobbins gets hurt again, which is a real possibility',
    risk: 'Buried on the depth chart unless an injury opens the door'
  },
  {
    player: 'Nicholas Singleton',
    pos: 'RB', team: 'TEN',
    category: 'Deep Sleeper',
    round: 'ADP ~233 / RB62',
    upside: 'Explosive rookie fifth-rounder in a genuinely open Titans backfield — Pollard and Spears both have real question marks',
    risk: 'Currently buried behind three other backs on the depth chart'
  },
  {
    player: 'Emmett Johnson',
    pos: 'RB', team: 'KC',
    category: 'Landing Spot Lottery',
    round: 'Deep-league stash',
    upside: 'Big Ten Running Back of the Year who fell to Round 5 on testing, not talent — the Chiefs landing him is a dream outcome',
    risk: 'Buried on the depth chart behind the incumbent starter for now'
  },
  {
    player: 'Tank Bigsby',
    pos: 'RB', team: 'PHI',
    category: 'Efficiency Bench Piece',
    round: 'Available outside top 150',
    upside: 'Averaged 5.9 yards/carry in a limited Eagles role last year and flashed a 104-yard game — clear RB2 insurance behind Saquon Barkley',
    risk: 'Barkley\'s workload leaves little room unless he\'s limited'
  },
  // ---- WR ----
  {
    player: 'Alec Pierce',
    pos: 'WR', team: 'IND',
    category: 'Volume Riser',
    round: "Colts' new clear-cut WR1",
    upside: 'Led the NFL at 21.3 yards/reception in 2025; signed a big new contract this offseason',
    risk: 'Boom/bust — averaged only 3.1 catches/game; low floor even with big-play ceiling'
  },
  {
    player: 'DeVonta Smith',
    pos: 'WR', team: 'PHI',
    category: 'Post-Trade Value',
    round: 'ADP ~ Round 3',
    upside: 'Inherits the Eagles\' clear WR1 role now that A.J. Brown was sent to New England; hit 1,000 yards even in a bottom-10 passing offense last year',
    risk: 'Philly\'s offensive identity still runs through the ground game'
  },
  {
    player: "De'Zhaun Stribling",
    pos: 'WR', team: 'SF',
    category: 'Rookie Opportunity',
    round: 'Late-round dart throw',
    upside: 'Slots in as SF\'s No. 3 target with Ricky Pearsall out for the year; familiar territory in a Kyle Shanahan offense',
    risk: 'Now sharing snaps with newly-signed veterans Mike Evans and Deebo Samuel Sr., not a clean path to volume'
  },
  {
    player: 'Rome Odunze',
    pos: 'WR', team: 'CHI',
    category: 'Injury Beneficiary',
    round: 'ADP climbing as camp progresses',
    upside: 'Poised for a bump in early-season targets while Luther Burden III (groin) is expected to miss the preseason',
    risk: 'Burden is expected back for Week 1, capping the runway'
  },
  {
    player: 'Jordyn Tyson',
    pos: 'WR', team: 'NO',
    category: 'Rookie Speed',
    round: 'Deep-league dart throw',
    upside: 'Gives New Orleans a legitimate explosive threat if he stays healthy through camp',
    risk: 'Rookie WR volatility, tied to Shough\'s development'
  },
  {
    player: 'Josh Downs',
    pos: 'WR', team: 'IND',
    category: 'Value Pick',
    round: 'Colts No. 2 option',
    upside: 'Reliable slot role behind Alec Pierce in a top-ranked Colts offense',
    risk: 'Dealing with a minor groin issue in camp; ceiling capped by Pierce\'s target share'
  },
  {
    player: 'Tank Dell',
    pos: 'WR', team: 'HOU',
    category: 'Post-Hype Sleeper',
    round: 'ADP ~ Round 15',
    upside: 'Back in full pads and cleared to practice for the first time since injury; explosive YAC threat when healthy',
    risk: 'Long layoff — real injury risk, but the price makes it a low-cost gamble'
  },
  {
    player: 'Stefon Diggs',
    pos: 'WR', team: 'WAS',
    category: 'Fresh Start',
    round: 'ADP still settling',
    upside: 'Caught 85 passes for 1,013 yards with New England last year; now paired with Jayden Daniels after an August signing',
    risk: 'Turns 32 this year, and joining a new offense in August creates early-season uncertainty'
  },
  {
    player: 'Jayden Higgins',
    pos: 'WR', team: 'HOU',
    category: 'Sophomore Riser',
    round: 'Part of the Iowa State duo',
    upside: 'Flashed real talent as a rookie; Houston moved on from Christian Kirk, opening up more target share',
    risk: 'Target competition with Nico Collins, Tank Dell and Jaylin Noel'
  },
  {
    player: 'Jaylin Noel',
    pos: 'WR', team: 'HOU',
    category: 'Sophomore Riser',
    round: 'Part of the Iowa State duo',
    upside: 'Houston\'s revamped offensive line and tempo should create more volume to go around',
    risk: 'Same crowded target competition as Higgins'
  },
  {
    player: 'Emeka Egbuka',
    pos: 'WR', team: 'TB',
    category: 'Vacated Role',
    round: 'Rising fast in August',
    upside: 'With Mike Evans now in San Francisco, the door is wide open for Egbuka to become Tampa Bay\'s top target — a detailed route runner who creates his own separation',
    risk: 'Still needs to prove he can carry a true WR1 workload'
  },
  // ---- TE ----
  {
    player: 'Isaiah Likely',
    pos: 'TE', team: 'NYG',
    category: 'Coaching Reunion',
    round: 'ADP ~ Round 8-9',
    upside: "Followed HC John Harbaugh from Baltimore to New York; building chemistry with Jaxson Dart, no Mark Andrews competing for targets anymore",
    risk: 'Unproven as a true TE1 workload outside Baltimore\'s system'
  },
  {
    player: 'Jake Tonges',
    pos: 'TE', team: 'SF',
    category: 'Injury Handcuff',
    round: 'Late-round streamer/stash',
    upside: 'Direct George Kittle replacement if Kittle opens the year on PUP; caught 5 TDs filling in last season',
    risk: "Value evaporates fast — Kittle is trending toward a Week 1 return"
  },
  {
    player: 'Greg Dulcich',
    pos: 'TE', team: 'MIA',
    category: 'Efficiency Darling',
    round: 'Mostly undrafted',
    upside: 'Ranked top-6 among TEs in targets/route and yards/route run in 2025; Miami\'s receiving corps still lacks a clear high-volume option',
    risk: 'Going undrafted in most leagues for a reason — role still needs to be earned'
  },
  {
    player: 'Chig Okonkwo',
    pos: 'TE', team: 'WAS',
    category: 'Fresh Start',
    round: 'Washington\'s new primary receiving TE',
    upside: '56 catches for 560 yards with Tennessee last year; now paired with Jayden Daniels, who has a track record of fantasy-relevant tight ends',
    risk: 'Stefon Diggs\' arrival in Washington could cut into his target share'
  },
  {
    player: 'Dalton Kincaid',
    pos: 'TE', team: 'BUF',
    category: 'Analytics Darling',
    round: 'Late-round TE1 upside',
    upside: 'His 1.8 yards/route run since 2023 trails only Kittle, McBride and Bowers among qualified tight ends; healthy entering his fourth year',
    risk: 'Buffalo\'s offense has other mouths to feed at receiver'
  },
  {
    player: 'Gunnar Helm',
    pos: 'TE', team: 'TEN',
    category: 'Vacated Role',
    round: 'Deep-league flier',
    upside: "Set a Titans rookie-TE franchise reception record (44 catches) last year; Chig Okonkwo's departure clears the position's receiving hierarchy for him",
    risk: 'Unproven as the clear-cut No. 1 target at the position'
  },
  {
    player: 'Jake Raridon',
    pos: 'TE', team: 'NE',
    category: 'Injury Handcuff',
    round: 'ADP ~ TE44',
    upside: "Josh McDaniels' offenses historically use multiple-TE sets; direct beneficiary if Hunter Henry (age 32) misses time",
    risk: 'Purely matchup/injury-contingent value behind an established starter'
  }
];

// Sourced from live training-camp coverage (FantasyPros, Yahoo Sports,
// Football Nation, ESPN/AJC joint-practice reporting) as of August 20, 2026.
const INJURIES = [
  {
    player: 'Ricky Pearsall',
    pos: 'WR', team: 'SF',
    status: 'Out for Season / PCL Surgery',
    severity: 'out',
    handcuff: "De'Zhaun Stribling",
    handcuffNote: '(SF WR — SF also signed veteran Deebo Samuel Sr. to fill the void)',
    recommendation: 'Off the board for redraft — target the handcuff sleeper instead'
  },
  {
    player: 'George Kittle',
    pos: 'TE', team: 'SF',
    status: 'PUP / Achilles Recovery — trending toward Week 1',
    severity: 'questionable',
    handcuff: 'Jake Tonges',
    handcuffNote: '(SF TE, splits reps with Luke Farrell if Kittle opens on PUP)',
    recommendation: 'Kittle is targeting a Sept. 10 return vs. the Rams — draft as a discounted TE1 with a Week 1-4 contingency plan'
  },
  {
    player: 'Christian McCaffrey',
    pos: 'RB', team: 'SF',
    status: 'Day-to-Day / Calf & Soft-Tissue Tightness',
    severity: 'day-to-day',
    handcuff: 'Isaac Guerendo',
    handcuffNote: '(SF RB, also on PUP but expected back Week 1)',
    recommendation: 'Not a red flag yet, but monitor camp reports closely before draft day'
  },
  {
    player: 'Michael Penix Jr.',
    pos: 'QB', team: 'ATL',
    status: 'Not Yet Cleared for 11-on-11 / ACL Recovery',
    severity: 'out',
    handcuff: 'Tua Tagovailoa',
    handcuffNote: '(ATL QB — leading the job by default, but struggling in camp)',
    recommendation: 'Speculative late-round stash only; ADP has drifted into the 260s while he\'s sidelined'
  },
  {
    player: 'Anthony Richardson',
    pos: 'QB', team: 'IND',
    status: 'Roster Uncertainty — Requested Trade',
    severity: 'questionable',
    handcuff: 'Daniel Jones',
    handcuffNote: "(IND QB, ahead of him — Jones looks 'flawless' returning from his own Achilles tear)",
    recommendation: 'Dynasty stash only if he\'s dealt — not draftable as a Colts backup in redraft'
  },
  {
    player: 'Malik Nabers',
    pos: 'WR', team: 'NYG',
    status: 'Recovering from ACL Tear — trending well',
    severity: 'questionable',
    handcuff: "Wan'Dale Robinson",
    handcuffNote: '(NYG WR, next in line for target share if Nabers is limited)',
    recommendation: 'Nabers is back practicing and on track for Week 1 — a discount worth buying if his ADP hasn\'t corrected yet'
  }
];

const SLEEPER_NAMES = new Set(SLEEPERS.map(s => s.player));

function findPlayerByName(name) {
  return PLAYERS.find(p => p.player === name) || null;
}
